// All editable site copy, English + Arabic, in one place.

export const content = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      experience: "Experience",
      projects: "Work",
      courses: "Courses",
      contact: "Contact",
    },
    profile: {
      name: "Islam El-sayed",
      roles: [
        "Full-Stack Developer",
        "UI/UX Designer",
        "Digital Marketing Instructor",
        "E-commerce Specialist",
        "SEO Specialist",
        "Web Designer",
      ],
      bio: "I build complete web products end to end — fast, accessible interfaces, solid back-end systems, and digital marketing strategy that actually moves the needle. Alongside client work, I teach programming, digital marketing and e-commerce to the next generation of developers and entrepreneurs.",
      badge: "Available for freelance & instructor collaborations",
      email: "islamshawqi525@gmail.com",
      phoneDisplay: "+971 50 669 6478",
      whatsapp: "https://wa.me/971506696478",
      cta: {
        contact: "Get in touch",
        work: "See my work",
      },
      social: {
        github: "https://github.com/islamel-sayed96",
        linkedin: "https://www.linkedin.com/in/islam-el-sayed-ab9252191",
        instagram: "https://www.instagram.com/islam.elsayed.shawqi/",
        facebook: "https://www.facebook.com/profile.php?id=100002621619161",
        behance: "https://www.behance.net/islamshawqi",
      },
    },
    stats: [
      { value: 5, suffix: "+", label: "Years of experience" },
      { value: 30, suffix: "+", label: "Projects delivered" },
      { value: 3, suffix: "", label: "Teaching institutes" },
      { value: 6, suffix: "+", label: "Courses taught" },
    ],
    skillsSection: {
      kicker: "What I do",
      title: "Full-spectrum product & growth expertise",
    },
    skills: [
      {
        icon: "Code2",
        title: "Front-End Development",
        desc: "Fast, accessible interfaces with React, Angular, TypeScript and modern tooling.",
      },
      {
        icon: "Server",
        title: "Back-End Development",
        desc: "Robust systems with C#, ASP.NET, and relational databases — built to scale.",
      },
      {
        icon: "PenTool",
        title: "UI/UX Design",
        desc: "Research-driven design from wireframe to polished, user-tested interface.",
      },
      {
        icon: "TrendingUp",
        title: "Digital Marketing & SEO",
        desc: "Content strategy and search visibility that produces measurable results.",
      },
      {
        icon: "LayoutTemplate",
        title: "Web Design",
        desc: "Modern landing pages and brand sites with a distinct visual identity.",
      },
      {
        icon: "ShoppingCart",
        title: "E-commerce",
        desc: "End-to-end stores: payment gateways, inventory, fulfillment, and marketplace selling.",
      },
    ],
    toolsSection: {
      kicker: "Toolbox",
      title: "Tools & technologies I work with",
      devLabel: "Development & Design",
      marketingLabel: "Marketing & E-commerce",
    },
    experienceSection: {
      kicker: "Career path",
      title: "Where I've worked",
    },
    experience: [
      {
        company: "Route",
        role: "Full-Stack Developer (Internship)",
        period: "Nov 2022 — Jul 2023",
        location: "Alexandria, Egypt",
        desc: "Hands-on training in full-stack web development, focused on Angular front-end engineering.",
      },
      {
        company: "ITI — Information Technology Institute",
        role: "Mentor",
        period: "Feb 2024 — Jul 2024",
        location: "Egypt",
        desc: "Mentored trainees through programming fundamentals and front-end development.",
      },
      {
        company: "Lifestyle Luxury Vacation Club (LLVC)",
        role: "Account Manager",
        period: "Sep 2024 — Dec 2024",
        location: "Dubai, UAE",
        desc: "Managed client accounts and relationships for a luxury vacation membership club.",
      },
      {
        company: "Al Bayan Institute",
        role: "Full-Stack Engineer & Instructor",
        period: "Sep 2024 — Present",
        location: "Dubai, UAE",
        desc: "Teaching e-commerce, web design and software engineering, alongside hands-on work in website development, SEO, ad campaign management, page management and administrative operations.",
        current: true,
      },
      {
        company: "NTC",
        role: "Instructor",
        period: "Mar 2025 — Present",
        location: "UAE",
        desc: "Teaching software engineering and e-commerce.",
        current: true,
      },
      {
        company: "Al-Waseet",
        role: "Instructor",
        period: "2025 — Present",
        location: "UAE",
        desc: "Teaching digital marketing and e-commerce.",
        current: true,
      },
    ],
    projectsSection: {
      kicker: "Selected work",
      title: "Projects & client engagements",
      viewSite: "Visit site",
      viewPage: "Visit page",
      all: "All",
    },
    projectCategories: {
      "Full-Stack": "Full-Stack",
      "Marketing & SEO": "Marketing & SEO",
      "Web Development": "Web Development",
    },
    projects: [
      {
        key: "darbna",
        title: "Darbna",
        subtitle: "Online course platform",
        desc: "A complete learning platform: video courses, interactive quizzes, certificates, live sessions and subscriptions — built with Laravel and React.",
        tags: ["Laravel", "React", "Inertia.js", "Tailwind"],
        category: "Full-Stack",
        href: "https://github.com/islamel-sayed96/Darbna",
        external: true,
        cta: "View on GitHub",
      },
      {
        key: "albyanhomes",
        title: "Al Bayan Homes",
        desc: "Website development, SEO, and paid ad campaign management.",
        tags: ["Website", "SEO", "Ads Management"],
        category: "Marketing & SEO",
        href: "https://albyanhomes.com/",
        external: true,
      },
      {
        key: "nmc",
        title: "NMC",
        desc: "Website development, SEO, social media page management, and ad campaign management.",
        tags: ["Website", "SEO", "Social Media", "Ads"],
        category: "Marketing & SEO",
        href: "https://nmc.ae/",
        external: true,
      },
      {
        key: "ntc",
        title: "NTC Emirates",
        desc: "Ad campaign management, SEO, and social media page management.",
        tags: ["Ads Management", "SEO", "Social Media"],
        category: "Marketing & SEO",
        href: "https://www.instagram.com/ntcemirates.ae/",
        external: true,
        cta: "View page",
      },
      {
        key: "albyaninstitute",
        title: "Al Bayan Institute",
        desc: "Website, SEO, campaign & page management, CRM systems, and administrative operations.",
        tags: ["Website", "SEO", "CRM", "Operations"],
        category: "Web Development",
        href: "https://albyan.institute/",
        external: true,
      },
      {
        key: "luvalle",
        title: "Luvalle Beauty Center",
        desc: "Website, SEO, campaign & page management, CRM systems, and operations.",
        tags: ["Website", "SEO", "CRM", "Operations"],
        category: "Web Development",
        href: "https://luvallebeautycenter.com/",
        external: true,
      },
      {
        key: "rahhaal",
        title: "Rahhaal",
        desc: "Full website design and development.",
        tags: ["Website"],
        category: "Web Development",
        href: "https://rahhaal.com/",
        external: true,
      },
    ],
    coursesSection: {
      kicker: "Training courses",
      title: "Learn directly from my experience",
      desc: "Every subject includes recorded lectures, interactive quizzes, and a complete reference page you can revisit anytime. This section is under construction.",
      cta: "Register your interest",
    },
    courses: [
      { title: "HTML & CSS for Beginners", lessons: 24, quizzes: 6 },
      { title: "JavaScript — Zero to Pro", lessons: 38, quizzes: 10 },
      { title: "React in Practice", lessons: 30, quizzes: 8 },
      { title: "Digital Marketing", lessons: 20, quizzes: 6 },
      { title: "E-commerce Fundamentals", lessons: 22, quizzes: 7 },
      { title: "Selling on Amazon & Noon", lessons: 18, quizzes: 5 },
    ],
    courseFeatures: {
      lessons: "recorded lectures",
      quizzes: "interactive quizzes",
      material: "full reference page",
    },
    contactSection: {
      kicker: "Get in touch",
      title: "Have a project or an idea?",
      desc: "Open to freelance projects, technical consulting, and designing custom training programs.",
      whatsapp: "WhatsApp",
    },
    footer: {
      rights: "All rights reserved.",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
    },
    aboutPage: {
      kicker: "About me",
      title: "The story behind the work",
      paragraphs: [
        "Hello there! I'm Islam El-sayed, a full-stack developer and digital marketer graduated from the Information Technology Institute (ITI), originally trained on the ASP.NET stack (C#, MSSQL, LINQ & Entity Framework, WinForms, ASP.NET MVC / Core / Web API) with a solid grounding in object-oriented programming.",
        "From there I branched into modern front-end engineering — React, Angular, TypeScript — and UI/UX design, taking products from wireframe through to a polished, user-tested interface in Figma.",
        "Today my work sits at the intersection of building and growing: I design and ship full web products end to end, and I run the digital marketing side too — SEO, paid ad campaigns, social media management, and CRM/operations — for real estate, education, and beauty-industry clients across the UAE.",
        "Alongside client work, I teach — software engineering, web design, e-commerce, and digital marketing — at multiple institutes in Dubai, mentoring the next generation of developers and entrepreneurs through hands-on, practical training.",
        "I consider myself a fast learner, a team player, a curious and disciplined person — always comfortable moving between the technical and the strategic side of a project.",
      ],
      skillGroups: [
        {
          title: "UI/UX",
          items: [
            "Figma",
            "Notion",
            "User Flow",
            "Prototyping",
            "Persona Development",
            "UI Design",
            "Mobile Design",
            "Dashboard Design",
            "Wireframing",
            "User Research",
            "Usability Testing",
            "UX Design",
          ],
        },
        {
          title: "Front-End",
          items: [
            "JavaScript",
            "TypeScript",
            "React.js",
            "Angular",
            "HTML5",
            "CSS3",
            "Sass",
            "Bootstrap",
            "Tailwind CSS",
            "jQuery",
          ],
        },
        {
          title: "Back-End",
          items: [
            "C#",
            ".NET / ASP.NET Core",
            "ASP.NET MVC",
            "Web API",
            "Microsoft SQL Server",
            "LINQ & Entity Framework",
            "WinForms",
            "OOP",
            "Unit Testing",
          ],
        },
        {
          title: "Marketing & E-commerce",
          items: [
            "SEO",
            "Paid Ad Campaigns",
            "Social Media Management",
            "CRM Systems",
            "E-commerce Operations",
            "Amazon & Noon Selling",
          ],
        },
      ],
      cta: "Get in touch",
    },
    theme: { light: "Light", dark: "Dark" },
    langToggle: "العربية",
  },

  ar: {
    nav: {
      home: "الرئيسية",
      about: "نبذة عني",
      skills: "المهارات",
      experience: "الخبرات",
      projects: "أعمالي",
      courses: "الدورات",
      contact: "تواصل",
    },
    profile: {
      name: "إسلام السيد",
      roles: [
        "مطوّر Full-Stack",
        "مصمم UI/UX",
        "مدرّب تسويق رقمي",
        "متخصص تجارة إلكترونية",
        "متخصص SEO",
        "مصمم مواقع",
      ],
      bio: "بصمم وبطوّر منتجات ويب متكاملة من الفكرة للإطلاق — واجهات سريعة وواضحة، أنظمة باك إند قوية، واستراتيجية تسويق رقمي بتحقق نتائج فعلية. وبجانب شغلي مع العملاء، بدرّس البرمجة والتسويق الرقمي والتجارة الإلكترونية لجيل جديد من المطورين ورواد الأعمال.",
      badge: "متاح لمشاريع الفريلانس والتعاون كمحاضر",
      email: "islamshawqi525@gmail.com",
      phoneDisplay: "+971 50 669 6478",
      whatsapp: "https://wa.me/971506696478",
      cta: {
        contact: "تواصل معي",
        work: "شوف أعمالي",
      },
      social: {
        github: "https://github.com/islamel-sayed96",
        linkedin: "https://www.linkedin.com/in/islam-el-sayed-ab9252191",
        instagram: "https://www.instagram.com/islam.elsayed.shawqi/",
        facebook: "https://www.facebook.com/profile.php?id=100002621619161",
        behance: "https://www.behance.net/islamshawqi",
      },
    },
    stats: [
      { value: 5, suffix: "+", label: "سنوات خبرة" },
      { value: 30, suffix: "+", label: "مشروع منجز" },
      { value: 3, suffix: "", label: "جهات تدريسية" },
      { value: 6, suffix: "+", label: "دورة تدريبية" },
    ],
    skillsSection: {
      kicker: "مجالات عملي",
      title: "خبرة متكاملة في المنتج والنمو",
    },
    skills: [
      {
        icon: "Code2",
        title: "Front-End Development",
        desc: "واجهات سريعة وسهلة الوصول بـ React وAngular وTypeScript وأحدث الأدوات.",
      },
      {
        icon: "Server",
        title: "Back-End Development",
        desc: "أنظمة قوية بـ C# وASP.NET وقواعد بيانات علائقية مصممة للنمو.",
      },
      {
        icon: "PenTool",
        title: "UI/UX Design",
        desc: "تصميم مبني على البحث من الـ wireframe لواجهة نهائية مُختبرة مع المستخدمين.",
      },
      {
        icon: "TrendingUp",
        title: "التسويق الرقمي و SEO",
        desc: "استراتيجية محتوى وتحسين ظهور في محركات البحث بنتائج قابلة للقياس.",
      },
      {
        icon: "LayoutTemplate",
        title: "تصميم مواقع",
        desc: "صفحات هبوط ومواقع تعريفية عصرية بهوية بصرية مميزة.",
      },
      {
        icon: "ShoppingCart",
        title: "التجارة الإلكترونية",
        desc: "متاجر متكاملة: بوابات دفع، مخزون، شحن، والبيع عبر المنصات الكبرى.",
      },
    ],
    toolsSection: {
      kicker: "أدواتي",
      title: "الأدوات والتقنيات اللي بشتغل بيها",
      devLabel: "تطوير وتصميم",
      marketingLabel: "تسويق وتجارة إلكترونية",
    },
    experienceSection: {
      kicker: "المسار المهني",
      title: "أماكن اشتغلت فيها",
    },
    experience: [
      {
        company: "Route",
        role: "مطوّر Full-Stack (تدريب)",
        period: "نوفمبر ٢٠٢٢ — يوليو ٢٠٢٣",
        location: "الإسكندرية، مصر",
        desc: "تدريب عملي على تطوير الويب المتكامل، بالتركيز على Angular في الفرونت إند.",
      },
      {
        company: "ITI — معهد تكنولوجيا المعلومات",
        role: "Mentor",
        period: "فبراير ٢٠٢٤ — يوليو ٢٠٢٤",
        location: "مصر",
        desc: "إشراف وتوجيه متدربين في أساسيات البرمجة وتطوير الواجهات الأمامية.",
      },
      {
        company: "Lifestyle Luxury Vacation Club (LLVC)",
        role: "Account Manager",
        period: "سبتمبر ٢٠٢٤ — ديسمبر ٢٠٢٤",
        location: "دبي، الإمارات",
        desc: "إدارة حسابات وعلاقات العملاء لنادي عضوية إجازات فاخر.",
      },
      {
        company: "معهد البيان",
        role: "Full-Stack Engineer & Instructor",
        period: "سبتمبر ٢٠٢٤ — حتى الآن",
        location: "دبي، الإمارات",
        desc: "تدريس التجارة الإلكترونية وتصميم المواقع وهندسة البرمجيات، بجانب العمل الفعلي في تطوير الموقع، SEO، إدارة الحملات الإعلانية، إدارة الصفحات، وتنظيم بعض الأعمال الإدارية.",
        current: true,
      },
      {
        company: "NTC",
        role: "محاضر",
        period: "مارس ٢٠٢٥ — حتى الآن",
        location: "الإمارات",
        desc: "تدريس هندسة البرمجيات والتجارة الإلكترونية.",
        current: true,
      },
      {
        company: "الوسيط",
        role: "محاضر",
        period: "٢٠٢٥ — حتى الآن",
        location: "الإمارات",
        desc: "تدريس التسويق الإلكتروني والتجارة الإلكترونية.",
        current: true,
      },
    ],
    projectsSection: {
      kicker: "أعمال مختارة",
      title: "مشاريع وعملاء اشتغلت معاهم",
      viewSite: "زيارة الموقع",
      viewPage: "زيارة الصفحة",
      all: "الكل",
    },
    projectCategories: {
      "Full-Stack": "Full-Stack",
      "Marketing & SEO": "تسويق و SEO",
      "Web Development": "تطوير مواقع",
    },
    projects: [
      {
        key: "darbna",
        title: "دربنا",
        subtitle: "منصة كورسات أونلاين",
        desc: "منصة تعليمية متكاملة: كورسات فيديو، اختبارات تفاعلية، شهادات، حصص مباشرة، واشتراكات — مبنية بـ Laravel وReact.",
        tags: ["Laravel", "React", "Inertia.js", "Tailwind"],
        category: "Full-Stack",
        href: "https://github.com/islamel-sayed96/Darbna",
        external: true,
        cta: "شوف المشروع على GitHub",
      },
      {
        key: "albyanhomes",
        title: "Al Bayan Homes",
        desc: "تطوير الموقع الإلكتروني، تحسين محركات البحث (SEO)، وإدارة الحملات الإعلانية الممولة.",
        tags: ["Website", "SEO", "Ads Management"],
        category: "Marketing & SEO",
        href: "https://albyanhomes.com/",
        external: true,
      },
      {
        key: "nmc",
        title: "NMC",
        desc: "تطوير الموقع الإلكتروني، SEO، إدارة صفحات السوشيال ميديا، وإدارة الحملات الإعلانية.",
        tags: ["Website", "SEO", "Social Media", "Ads"],
        category: "Marketing & SEO",
        href: "https://nmc.ae/",
        external: true,
      },
      {
        key: "ntc",
        title: "NTC Emirates",
        desc: "إدارة الحملات الإعلانية، SEO، وإدارة صفحات السوشيال ميديا.",
        tags: ["Ads Management", "SEO", "Social Media"],
        category: "Marketing & SEO",
        href: "https://www.instagram.com/ntcemirates.ae/",
        external: true,
        cta: "زيارة الصفحة",
      },
      {
        key: "albyaninstitute",
        title: "Al Bayan Institute",
        desc: "الموقع الإلكتروني، SEO، إدارة الحملات والصفحات، أنظمة CRM، وتنظيم العمل الإداري.",
        tags: ["Website", "SEO", "CRM", "Operations"],
        category: "Web Development",
        href: "https://albyan.institute/",
        external: true,
      },
      {
        key: "luvalle",
        title: "Luvalle Beauty Center",
        desc: "الموقع الإلكتروني، SEO، إدارة الحملات والصفحات، أنظمة CRM، وتنظيم العمل.",
        tags: ["Website", "SEO", "CRM", "Operations"],
        category: "Web Development",
        href: "https://luvallebeautycenter.com/",
        external: true,
      },
      {
        key: "rahhaal",
        title: "Rahhaal",
        desc: "تصميم وتطوير الموقع الإلكتروني بالكامل.",
        tags: ["Website"],
        category: "Web Development",
        href: "https://rahhaal.com/",
        external: true,
      },
    ],
    coursesSection: {
      kicker: "الدورات التدريبية",
      title: "اتعلم منّي مباشرة من خبرتي",
      desc: "كل مادة فيها محاضرات مسجلة، اختبارات تفاعلية، وصفحة مرجعية كاملة ترجع لها وقت ما تحتاج. القسم ده قيد الإنشاء حاليًا.",
      cta: "سجّل اهتمامك",
    },
    courses: [
      { title: "HTML & CSS للمبتدئين", lessons: 24, quizzes: 6 },
      { title: "JavaScript من الصفر للاحتراف", lessons: 38, quizzes: 10 },
      { title: "React عملي", lessons: 30, quizzes: 8 },
      { title: "التسويق الإلكتروني", lessons: 20, quizzes: 6 },
      { title: "أساسيات التجارة الإلكترونية", lessons: 22, quizzes: 7 },
      { title: "البيع على أمازون ونون", lessons: 18, quizzes: 5 },
    ],
    courseFeatures: {
      lessons: "محاضرة مسجلة",
      quizzes: "اختبارات تفاعلية",
      material: "صفحة مرجعية كاملة",
    },
    contactSection: {
      kicker: "تواصل معي",
      title: "عندك مشروع أو فكرة؟",
      desc: "متاح لمشاريع الفريلانس، الاستشارات التقنية، وتصميم برامج تدريبية مخصصة.",
      whatsapp: "واتساب",
    },
    footer: {
      rights: "جميع الحقوق محفوظة.",
      terms: "الشروط والأحكام",
      privacy: "سياسة الخصوصية",
    },
    aboutPage: {
      kicker: "نبذة عني",
      title: "القصة اللي ورا الشغل",
      paragraphs: [
        "أهلاً بيك! أنا إسلام السيد، مطوّر Full-Stack ومتخصص تسويق رقمي، خريج معهد تكنولوجيا المعلومات (ITI)، وبدأت مساري على تقنيات ASP.NET (سي شارب، MSSQL، LINQ وEntity Framework، WinForms، ASP.NET MVC / Core / Web API) مع أساس قوي في البرمجة الكائنية (OOP).",
        "من هناك اتجهت لتطوير الواجهات الأمامية الحديثة — React، Angular، TypeScript — وتصميم UI/UX، من الـ wireframe لحد واجهة نهائية مُختبرة مع المستخدمين على Figma.",
        "النهارده شغلي بين حاجتين: بناء المنتج ونموّه. بصمم وأطوّر منتجات ويب متكاملة من الفكرة للإطلاق، وكمان بدير الجانب التسويقي — SEO، حملات إعلانية ممولة، إدارة سوشيال ميديا، وأنظمة CRM وعمليات تشغيلية — لعملاء في العقارات والتعليم ومراكز التجميل في الإمارات.",
        "وبجانب شغل العملاء، بدرّس — هندسة البرمجيات، تصميم المواقع، التجارة الإلكترونية، والتسويق الرقمي — في أكتر من معهد في دبي، وبساعد جيل جديد من المطورين ورواد الأعمال بتدريب عملي.",
        "بعتبر نفسي سريع التعلم، شغّال جماعي، فضولي ومنضبط — ومرتاح إني أتنقل بين الجانب التقني والاستراتيجي في أي مشروع.",
      ],
      skillGroups: [
        {
          title: "UI/UX",
          items: [
            "Figma",
            "Notion",
            "User Flow",
            "Prototyping",
            "Persona Development",
            "UI Design",
            "Mobile Design",
            "Dashboard Design",
            "Wireframing",
            "User Research",
            "Usability Testing",
            "UX Design",
          ],
        },
        {
          title: "Front-End",
          items: [
            "JavaScript",
            "TypeScript",
            "React.js",
            "Angular",
            "HTML5",
            "CSS3",
            "Sass",
            "Bootstrap",
            "Tailwind CSS",
            "jQuery",
          ],
        },
        {
          title: "Back-End",
          items: [
            "C#",
            ".NET / ASP.NET Core",
            "ASP.NET MVC",
            "Web API",
            "Microsoft SQL Server",
            "LINQ & Entity Framework",
            "WinForms",
            "OOP",
            "Unit Testing",
          ],
        },
        {
          title: "تسويق وتجارة إلكترونية",
          items: [
            "SEO",
            "حملات إعلانية ممولة",
            "إدارة سوشيال ميديا",
            "أنظمة CRM",
            "عمليات تجارة إلكترونية",
            "البيع على أمازون ونون",
          ],
        },
      ],
      cta: "تواصل معي",
    },
    theme: { light: "فاتح", dark: "داكن" },
    langToggle: "English",
  },
};
